In [2]:
import pandas as pd

In [27]:
data = pd.read_csv("../../data_sets/Facility_Data Pull.csv", low_memory=False)

In [33]:
print("Columns in raw data (id, name)")
for idx, name in enumerate(data.columns[45:]):
    print(idx + 45, ": ", name, sep="")

Columns in raw data (id, name)
45: Sub Type
46: Location
47: Injection(Mcf/d)
48: Shrinkage(Mcf/d)
49: Fuel(Mcf/d)
50: Flared(Mcf/d)
51: Other(Mcf/d)
52: Oil(Bbl/d)
53: Methane Plus (C1+)(Bbl/d)
54: Receipt of Ethane (C2)(Bbl/d)
55: Receipt of Ethane Plus (C2+)(Bbl/d)
56: Receipt of Propane (C3)(Bbl/d)
57: Receipt of Propane Plus (C3+)(Bbl/d)
58: Receipt of Butane (C4)(Bbl/d)
59: Receipt of Butane Plus (C4+)(Bbl/d)
60: Receipt of Pentane (C5)(Bbl/d)
61: Receipt of Pentane Plus (C5+)(Bbl/d)
62: Oil Production(Bbl/d)
63: Oil Received(Bbl/d)
64: Oil Open Inventory(Bbl/d)
65: Oil Close Inventory(Bbl/d)
66: Oil Delivered(Bbl/d)
67: Gas Production(Mcf/d)
68: Gas Received(Mcf/d)
69: Lease Fuel(Mcf/d)
70: Gas Flared(Mcf/d)
71: Gas Vented(Mcf/d)
72: Gas Meter Diff(Mcf/d)
73: Gas Delivered(Mcf/d)
74: Water Production(Bbl/d)
75: Water Received(Bbl/d)
76: Water Open Inventory(Bbl/d)
77: Water Close Inventory(Bbl/d)
78: Water Meter Diff(Bbl/d)
79: Water Delivered(Bbl/d)
80: Date
81: Raw Gas(Mcf/d).1
82: Sales Gas(Mcf/d).1
83: Injection(Mcf/d).1
84: Shrinkage(Mcf/d).1
85: Fuel(Mcf/d).1
86: Flared(Mcf/d).1
87: Other(Mcf/d).1
88: Oil(Bbl/d).1
89: Methane Plus (C1+)(Bbl/d).1
90: Ethane (C2)(Bbl/d).1
91: Ethane Plus (C2+)(Bbl/d).1
92: Propane (C3)(Bbl/d).1
93: Propane Plus (C3+)(Bbl/d)
94: Butane (C4)(Bbl/d).1
95: Butane Plus (C4+)(Bbl/d)
96: Pentane (C5)(Bbl/d)
97: Pentane Plus (C5+)(Bbl/d).1
98: Natural Gas Liquids(Bbl/d).1
99: Sulphur(ton/d).1
100: Receipt of Oil(Bbl/d)
101: Receipt of Ethane (C2)(Bbl/d).1
102: Receipt of Ethane Plus (C2+)(Bbl/d).1
103: Receipt of Propane (C3)(Bbl/d).1
104: Receipt of Propane Plus (C3+)(Bbl/d).1
105: Receipt of Butane (C4)(Bbl/d).1
106: Receipt of Butane Plus (C4+)(Bbl/d).1
107: Receipt of Pentane (C5)(Bbl/d).1
108: Receipt of Pentane Plus (C5+)(Bbl/d).1
109: Oil Production(Bbl/d).1
110: Oil Received(Bbl/d).1
111: Oil Open Inventory(Bbl/d).1
112: Oil Close Inventory(Bbl/d).1
113: Oil Delivered(Bbl/d).1
114: Gas Production(Mcf/d).1
115: Gas Received(Mcf/d).1
116: Lease Fuel(Mcf/d).1
117: Gas Flared(Mcf/d).1
118: Gas Vented(Mcf/d).1
119: Gas Meter Diff(Mcf/d).1
120: Gas Delivered(Mcf/d).1
121: Water Production(Bbl/d).1
122: Water Received(Bbl/d).1
123: Water Open Inventory(Bbl/d).1
124: Water Close Inventory(Bbl/d).1
125: Water Meter Diff(Bbl/d).1
126: Water Delivered(Bbl/d).1

In [36]:
data.columns = data.columns.str.replace('Unique Facility ID', 'id')

# Facility data
facilities = data.iloc[:, :13].drop_duplicates().reset_index(drop=True)

# Capacity data
facility_capacity = data.iloc[:, [0] + [45, 46] + list(range(13, 35))].drop_duplicates().reset_index(drop=True)

# Production data

# I believe this table includes total production, but might need to take a look at it with the next table
facility_total_production = data.iloc[:, [0] + list(range(35, 80))].drop_duplicates().reset_index(drop=True)

# This is MONTHLY production data for that facility by LSD, month, and year, also explains the facility type
facility_monthly_production = data.iloc[:, [0] + list(range(80, 127))].drop_duplicates().reset_index(drop=True)

# Add all data to a dictionary to loop over it and do high level analysis
data_dict = {
    "facilities": facilities,
    "facility_capacity": facility_capacity,
    "facility_total_production": facility_total_production,
    "facility_monthly_production": facility_monthly_production
}

In [37]:
for name, df in data_dict.items():
    print(f"Showing {name}:")
    display(df.head())

Showing facilities:

,id,Status,Name,Type,Plant Name,Current Operator,Original Operator,Co-Owner,Constructed Date,Activated Date,Field Name,Latitude,Longitude
0,ABGP0001001,Active,MAPLE GLEN 15-36-036-16W4,GP,MAPLE GLEN,CANADIAN NATURAL RESOURCES LIMITED,NaN,0.0% - CANSEARCH RESOURCES LTD.; 0.0% - CANADI...,NaN,NaN,NaN,52.14129 deg N,112.15592 deg W
1,ABGP0001002,Suspended,KEYERA NEVIS GAS PLANT 16-33-38-22W4,GP,NEVIS,KEYERA ENERGY LTD.,NaN,100.0% - KEYERA ENERGY LTD.,1956-01-01,NaN,NaN,52.31647 deg N,113.07704 deg W
2,ABGP0001003,Suspended,* GULF PINCHER CREEK,GP,PINCHER CREEK,GULF CANADA LIMITED,NaN,100.0% - PALMER RANCH (1984) LTD.,NaN,NaN,NaN,49.30742 deg N,113.79413 deg W
3,ABGP0001004,Active,KEYERA HOMEGLEN-RIMBEY 2-05-44-01W5,GP,RIMBEY,KEYERA ENERGY LTD.,NaN,0.0% - CENTIPEDE HOLDINGS LTD.; 0.8% - BELLATR...,1961-01-01,NaN,NaN,52.75748 deg N,114.10701 deg W
4,ABGP0001005,Suspended,* GULF GILBY,GP,GILBY,I3 ENERGY CANADA LTD.,NaN,100.0% - I3 ENERGY CANADA LTD.,NaN,NaN,NaN,52.44119 deg N,114.30526 deg W

Showing facility_capacity:

,id,Sub Type,Location,Licensed Capacity of Raw Gas(Mcf/d),Licensed Capacity of Sales Gas(Mcf/d),Licensed Capacity of Oil(Bbl/d),Licensed Capacity of Ethane (C2)(Bbl/d),Licensed Capacity of Ethane Plus (C2+)(Bbl/d),Licensed Capacity of Propane (C3)(Bbl/d),Licensed Capacity of Butane (C4)(Bbl/d),...,Design Capacity of Sales Gas(Mcf/d),Design Capacity of Oil(Bbl/d),Design Capacity of Ethane (C2)(Bbl/d),Design Capacity of Ethane Plus (C2+)(Bbl/d),Design Capacity of Propane (C3)(Bbl/d),Design Capacity of Butane (C4)(Bbl/d),Design Capacity of Pentane Plus (C5+)(Bbl/d),Design Capacity of NGL(Bbl/d),Design Capacity of LPG(Bbl/d),Design Capacity of Sulphur(ton/d)
0,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,50111.51,48345.77,NaN,0.00,NaN,0.00,0.00,...,9437.84,0.00,0.00,NaN,0.00,0.00,0.00,157.32,NaN,0.00
1,ABGP0001002,Gas Plant Sulphur Recovery,16-33-038-22W4M,150087.32,134301.66,NaN,0.00,NaN,1541.75,1258.57,...,110358.32,0.00,0.00,NaN,6292.87,5034.30,3775.72,0.00,NaN,55.12
2,ABGP0001003,Gas Plant Sulphur Recovery,01-23-004-29W4M,89557.98,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABGP0001004,Gas Plant Sulphur Recovery,02-05-044-01W5M,420880.15,353499.77,NaN,26115.41,0.0,18878.61,10068.59,...,335999.94,12585.74,11956.45,NaN,10188.16,7079.48,14247.06,18123.47,NaN,165.35
4,ABGP0001005,Gas Plant Sweet,06-13-040-03W5M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Showing facility_total_production:

,id,Raw Gas(Mcf/d),Sales Gas(Mcf/d),Ethane (C2)(Bbl/d),Ethane Plus (C2+)(Bbl/d),Propane (C3)(Bbl/d),Butane (C4)(Bbl/d),Pentane Plus (C5+)(Bbl/d),Natural Gas Liquids(Bbl/d),Liquefied Petroleum Gas(Bbl/d),...,Gas Flared(Mcf/d),Gas Vented(Mcf/d),Gas Meter Diff(Mcf/d),Gas Delivered(Mcf/d),Water Production(Bbl/d),Water Received(Bbl/d),Water Open Inventory(Bbl/d),Water Close Inventory(Bbl/d),Water Meter Diff(Bbl/d),Water Delivered(Bbl/d)
0,ABGP0001001,3201.67,2958.23,0.00,0.0,0.00,0.00,16.32,29.72,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABGP0001002,0.00,0.00,0.00,0.0,0.00,0.00,4.47,0.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABGP0001003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABGP0001004,201227.85,151844.16,12715.62,0.0,12074.45,7100.35,0.00,0.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABGP0001005,367268.84,217590.15,0.00,0.0,0.00,0.00,0.00,0.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Showing facility_monthly_production:

,id,Date,Raw Gas(Mcf/d).1,Sales Gas(Mcf/d).1,Injection(Mcf/d).1,Shrinkage(Mcf/d).1,Fuel(Mcf/d).1,Flared(Mcf/d).1,Other(Mcf/d).1,Oil(Bbl/d).1,...,Gas Flared(Mcf/d).1,Gas Vented(Mcf/d).1,Gas Meter Diff(Mcf/d).1,Gas Delivered(Mcf/d).1,Water Production(Bbl/d).1,Water Received(Bbl/d).1,Water Open Inventory(Bbl/d).1,Water Close Inventory(Bbl/d).1,Water Meter Diff(Bbl/d).1,Water Delivered(Bbl/d).1
0,ABGP0001001,Jul-90,27426.39,26439.06,0.0,127.93,344.15,0.0,515.25,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABGP0001001,Aug-90,29693.94,28807.77,0.0,143.54,403.84,0.0,338.79,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABGP0001001,Sep-90,29129.77,28372.51,0.0,138.08,372.69,0.0,246.50,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABGP0001001,Oct-90,22140.02,21020.43,0.0,117.68,293.34,0.0,708.57,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABGP0001001,Nov-90,20575.38,19470.62,0.0,87.46,302.18,0.0,715.12,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN